### ISSUE TITLE
Feature: Read Current Settings of One Camera

### ISSUE THREAD

**Issue by Olliebrown** [UWStout/simple-canon-control#3]
Ability to read out and summarize all relevant information for one connected camera

Information to read:
- All exposure settings
- Zoom setting
- Focus setting
- Focus and light metering mode
- Shooting mood dial setting
- Image type and quality settings

## Tasks to Complete:
- [ ] Open session with single camera
- [ ] Read out settings and print to console
- [ ] Print settings in JSON format
- [ ] Close session
