### ISSUE TITLE
Feature: Read settings for Multiple Cameras

### ISSUE THREAD

**Issue by Olliebrown** [UWStout/simple-canon-control#4]
Apply setting readout to all connected cameras.

## Tasks to Complete:
- [ ] Iterate over connected cameras
- [ ] Open session with one camera
- [ ] Read and print settings for that one camera (requires #3 complete)
